<a href="https://colab.research.google.com/github/abdulhakimarrauf-sys/Abdul-Hakim-Arrauf_Aljabar-Matrix/blob/main/Matrix_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
'**SOAL NO 1 (Matrix Tensors)**'

'**SOAL NO 1 (Matrix Tensors)**'

In [3]:
import numpy as np

In [5]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[19, 20, 10], [1, 9, 2]])
X

array([[19, 20, 10],
       [ 1,  9,  2]])

In [6]:
# tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [7]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([19,  1])

In [8]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([1, 9, 2])

In [9]:
"""**SOAL NO 2 (Matrix Tensors) (PyTorch)**"""

'**SOAL NO 2 (Matrix Tensors) (PyTorch)**'

In [10]:
# ulangi soal nomor 1 menggunakan pytorch
import torch

X_pt = torch.tensor([[19, 20, 10], [1, 9, 2]])
X_pt

X_pt.shape

X_pt[:,0]

X_pt[1,:]

tensor([1, 9, 2])

In [11]:
# ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

X_tf = tf.Variable([[19, 20, 10], [1, 9, 2]])
X_tf

tf.shape(X_tf)

X_tf[:,0]

X_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 9, 2], dtype=int32)>