<a href="https://colab.research.google.com/github/abdulhakimarrauf-sys/Abdul-Hakim-Arrauf_Aljabar-Matrix/blob/main/Vectors_and_Vector_Transposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'**SOAL NO 1 (VECTORS AND VECTOR TRANSPOSITION)**'


'**SOAL NO 1 (VECTORS AND VECTOR TRANSPOSITION)**'

In [2]:
# buat vector x dengan ukuran 3x1
import numpy as np

x = np.array([[19],
              [20],
              [10]])
x

array([[19],
       [20],
       [10]])

In [3]:
# hitung panjang vector x
len(x)

3

In [4]:
# tampilkan ukuran vector x
x.shape

(3, 1)

In [5]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [6]:
# akses elemen pertama dari vector x
x[0]

array([19])

In [7]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.ndarray

In [8]:
"""**SOAL NO 2 (VECTORS AND VECTOR TRANSPOSITION)**"""

'**SOAL NO 2 (VECTORS AND VECTOR TRANSPOSITION)**'

In [9]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_trans = x.T
x_trans

array([[19, 20, 10]])

In [10]:
# tampilkan ukuran dari vector x_t
x_trans.shape

(1, 3)

In [11]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[19],
              [20],
              [10]])
y

array([[19],
       [20],
       [10]])

In [ ]:
# tampilkan ukuran dari vector x_t
y.shape

In [ ]:
"""**SOAL NO 3 (VECTORS AND VECTOR TRANSPOSITION) (TENSORFLOW)**"""

In [12]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import tensorflow as tf

x_tf = tf.Variable([[19],
                    [20],
                    [10]])
x_tf

x_tf.shape

y_tf = tf.Variable([[19],
                    [20],
                    [10]])
y_tf

y_tf.shape

TensorShape([3, 1])

In [13]:
"""**SOAL NO 3 (VECTORS AND VECTOR TRANSPOSITION) (PYTORCH)**"""

'**SOAL NO 3 (VECTORS AND VECTOR TRANSPOSITION) (PYTORCH)**'

In [14]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch

x_pt = torch.tensor([[19],
                     [20],
                     [10]])
x_pt

x_pt.shape

y_pt = torch.tensor([[19],
                     [20],
                     [10]])
y_pt

y_pt.shape

torch.Size([3, 1])